import { extractExportNames } from './exports'
import { type ComponentEntry } from './scanner'

const HEADER = '// Generated by nojoy — do not edit\n'
const PREFIX = '_Nojoy$'

export function generateComponentTypes(
  component: ComponentEntry
): string | undefined {
  const asyncPath = component.concerns['async']
  const i18nPath = component.concerns['i18n']

  // Only generate if there are prop-injecting concerns
  if (!asyncPath && !i18nPath) return undefined

  const asyncExports = asyncPath ? extractExportNames(asyncPath) : []

  // Skip if async concern exists but has no exports
  if (asyncPath && asyncExports.length === 0 && !i18nPath) return undefined

  const lines: string[] = [HEADER]

  // Imports
  if (asyncExports.length > 0) {
    lines.push(`import { type AsyncHandler } from 'nojoy/runtime'`)
    const specifiers = asyncExports
      .map((name) => `type ${name} as ${PREFIX}${name}`)
      .join(', ')
    lines.push(`import { ${specifiers} } from './async'`)
  }

  if (i18nPath) {
    lines.push(`import type ${PREFIX}i18nDefaults from './i18n'`)
  }

  lines.push('')

  // Type helpers for async exports
  for (const name of asyncExports) {
    lines.push(`type ${PREFIX}${name}$Inner = ReturnType<${PREFIX}${name}>`)
  }

  if (asyncExports.length > 0) {
    lines.push('')
  }

  // InjectedProps interface (internal, not exported)
  lines.push(`interface ${PREFIX}InjectedProps {`)

  for (const name of asyncExports) {
    lines.push(
      `  ${name}: AsyncHandler<Parameters<${PREFIX}${name}$Inner>, Awaited<ReturnType<${PREFIX}${name}$Inner>>>`
    )
  }

  if (i18nPath) {
    lines.push(`  i18n: ReturnType<${PREFIX}i18nDefaults>`)
  }

  lines.push('}')
  lines.push('')

  // defineView — typed identity function for prop inference
  lines.push(
    `export function defineView<P extends Record<string, unknown> = Record<string, never>>(component: (props: ${PREFIX}InjectedProps & P) => any): typeof component {`
  )
  lines.push('  return component')
  lines.push('}')
  lines.push('')

  return lines.join('\n')
}
