// Generated by nojoy — do not edit

import { type AsyncHandler } from 'nojoy/runtime'
import { type click as _Nojoy$click } from './async'
import type _Nojoy$i18nDefaults from './i18n'

type _Nojoy$click$Inner = ReturnType<_Nojoy$click>

interface _Nojoy$InjectedProps {
  click: AsyncHandler<Parameters<_Nojoy$click$Inner>, Awaited<ReturnType<_Nojoy$click$Inner>>>
  i18n: ReturnType<_Nojoy$i18nDefaults>
}

export function defineView<P extends Record<string, unknown> = Record<string, never>>(component: (props: _Nojoy$InjectedProps & P) => any): typeof component {
  return component
}
