// Generated by nojoy — do not edit

import { type AsyncHandler } from 'nojoy/runtime'
import { type loadUsers as _Nojoy$loadUsers } from './async'

type _Nojoy$loadUsers$Inner = ReturnType<_Nojoy$loadUsers>

interface _Nojoy$InjectedProps {
  loadUsers: AsyncHandler<Parameters<_Nojoy$loadUsers$Inner>, Awaited<ReturnType<_Nojoy$loadUsers$Inner>>>
}

export function defineView<P extends Record<string, unknown> = Record<string, never>>(component: (props: _Nojoy$InjectedProps & P) => any): typeof component {
  return component
}
