import { resolve } from 'node:path'

import { describe, expect, it } from 'vitest'

import { generateComponentTypes } from '../../src/plugin/typegen'

import type { ComponentEntry } from '../../src/plugin/scanner'

const FIXTURES = resolve(__dirname, 'fixtures/basic')

describe('generateComponentTypes', () => {
  it('returns undefined when no prop-injecting concerns exist', () => {
    const component: ComponentEntry = {
      name: 'with-placeholder',
      dir: resolve(FIXTURES, 'components/with-placeholder'),
      viewPath: resolve(FIXTURES, 'components/with-placeholder/index.tsx'),
      concerns: {
        placeholder: resolve(
          FIXTURES,
          'components/with-placeholder/placeholder.tsx'
        ),
      },
    }

    expect(generateComponentTypes(component)).toBeUndefined()
  })

  it('generates AsyncHandler types for async-only component', () => {
    const component: ComponentEntry = {
      name: 'button',
      dir: resolve(FIXTURES, 'components/button'),
      viewPath: resolve(FIXTURES, 'components/button/index.tsx'),
      concerns: { async: resolve(FIXTURES, 'components/button/async.ts') },
    }

    const result = generateComponentTypes(component)!

    expect(result).toContain(
      "import { type AsyncHandler } from 'nojoy/runtime'"
    )
    expect(result).toContain(
      "import { type click as _Nojoy$click } from './async'"
    )
    expect(result).toContain(
      'type _Nojoy$click$Inner = ReturnType<_Nojoy$click>'
    )
    expect(result).toContain(
      'click: AsyncHandler<Parameters<_Nojoy$click$Inner>, Awaited<ReturnType<_Nojoy$click$Inner>>>'
    )
    expect(result).not.toContain('i18n')
  })

  it('generates i18n type for i18n-only component', () => {
    const component: ComponentEntry = {
      name: 'with-i18n',
      dir: resolve(FIXTURES, 'components/with-i18n'),
      viewPath: resolve(FIXTURES, 'components/with-i18n/index.tsx'),
      concerns: { i18n: resolve(FIXTURES, 'components/with-i18n/i18n.ts') },
    }

    const result = generateComponentTypes(component)!

    expect(result).toContain("import type _Nojoy$i18nDefaults from './i18n'")
    expect(result).toContain('i18n: ReturnType<_Nojoy$i18nDefaults>')
    expect(result).not.toContain('AsyncHandler')
  })

  it('generates both types for async + i18n component', () => {
    const component: ComponentEntry = {
      name: 'button',
      dir: resolve(FIXTURES, 'components/button'),
      viewPath: resolve(FIXTURES, 'components/button/index.tsx'),
      concerns: {
        async: resolve(FIXTURES, 'components/button/async.ts'),
        i18n: resolve(FIXTURES, 'components/button/i18n.ts'),
      },
    }

    const result = generateComponentTypes(component)!

    expect(result).toContain('AsyncHandler')
    expect(result).toContain('click:')
    expect(result).toContain('i18n: ReturnType<_Nojoy$i18nDefaults>')
  })

  it('handles multiple async exports', () => {
    const component: ComponentEntry = {
      name: 'form',
      dir: resolve(FIXTURES, 'components/form'),
      viewPath: resolve(FIXTURES, 'components/form/index.tsx'),
      concerns: { async: resolve(FIXTURES, 'components/form/async.ts') },
    }

    const result = generateComponentTypes(component)!

    expect(result).toContain('submit:')
  })

  it('includes header comment', () => {
    const component: ComponentEntry = {
      name: 'button',
      dir: resolve(FIXTURES, 'components/button'),
      viewPath: resolve(FIXTURES, 'components/button/index.tsx'),
      concerns: { async: resolve(FIXTURES, 'components/button/async.ts') },
    }

    const result = generateComponentTypes(component)!

    expect(result).toMatch(/^\/\/ Generated by nojoy/)
  })

  it('exports defineView function', () => {
    const component: ComponentEntry = {
      name: 'button',
      dir: resolve(FIXTURES, 'components/button'),
      viewPath: resolve(FIXTURES, 'components/button/index.tsx'),
      concerns: { async: resolve(FIXTURES, 'components/button/async.ts') },
    }

    const result = generateComponentTypes(component)!

    expect(result).toContain('export function defineView')
    expect(result).toContain('_Nojoy$InjectedProps')
  })
})
