// Generated by nojoy — do not edit

import { type AsyncHandler } from 'nojoy/runtime'
import { type loadPosts as _Nojoy$loadPosts } from './async'

type _Nojoy$loadPosts$Inner = ReturnType<_Nojoy$loadPosts>

interface _Nojoy$InjectedProps {
  loadPosts: AsyncHandler<Parameters<_Nojoy$loadPosts$Inner>, Awaited<ReturnType<_Nojoy$loadPosts$Inner>>>
}

export function defineView<P extends Record<string, unknown> = Record<string, never>>(component: (props: _Nojoy$InjectedProps & P) => any): typeof component {
  return component
}
